/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppv.forms;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ppv.model.Productos;

/**
 *
 * @author user2
 */
public class BuscadorProductos extends javax.swing.JFrame {
    
    DefaultTableModel productosEncontradosAModificar;
    Productos productoParaCarrrito=new Productos();
    Venta ventanaAnt;
    public BuscadorProductos(DefaultTableModel productosEncontradosAModificar,Venta ventanaAnt) {
       
        this.productosEncontradosAModificar=productosEncontradosAModificar;
        initComponents();
        setLocationRelativeTo(null);
        //listaProductosAModificar.getColumn("Precio compra").setWidth(0);
        //listaProductosAModificar.getColumn("Precio compra").setMinWidth(0);
        //listaProductosAModificar.getColumn("Precio compra").setMaxWidth(0);
        this.ventanaAnt=ventanaAnt;
    }
    public BuscadorProductos() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaProductosAModificar = new javax.swing.JTable();
        agregarProductoAVenta = new javax.swing.JButton();
        cantidadProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        listaProductosAModificar.setModel(productosEncontradosAModificar);
        jScrollPane5.setViewportView(listaProductosAModificar);

        agregarProductoAVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ppv/forms/1448503432_sign-add.png"))); // NOI18N
        agregarProductoAVenta.setText("Agregar producto");
        agregarProductoAVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoAVentaActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad que deseas agregar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(agregarProductoAVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarProductoAVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProductoAVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoAVentaActionPerformed
        
        int fila=listaProductosAModificar.getSelectedRowCount();
        
        if(fila==0){
            JOptionPane.showMessageDialog(null,"No has seleccionado un producto para agregar");
            return;
        }else{
            fila=fila-1;
        } 
        int cantidad=0;
        Double cantidatD=0.0;
        if(!cantidadProd.getText().equals("")){
            if(cantidadProd.getText().contains(".")){
                cantidatD=Double.parseDouble(cantidadProd.getText());
            }else{
               cantidad=Integer.parseInt(cantidadProd.getText());
            }  
        }else{
             JOptionPane.showMessageDialog(null,"No se introdujo cantidad a agregar");
             return;
        }
        
        
         productoParaCarrrito=new Productos();
         productoParaCarrrito.setId(""+listaProductosAModificar.getValueAt(listaProductosAModificar.getSelectedRow(), 0));
         
         if(cantidatD!=0.0){
            productoParaCarrrito.setUnidadesEnCaja(cantidatD);
         }else{
            productoParaCarrrito.setUnidadesEnCaja((1.0*cantidad));
         }
         ventanaAnt.setProductoParaCarrritoDesdeOtraVentana(productoParaCarrrito);
         ventanaAnt.lectorCBFinalizoLectura();
         this.setVisible(false);
    }//GEN-LAST:event_agregarProductoAVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscadorProductos().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProductoAVenta;
    private javax.swing.JTextField cantidadProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane5;
    private static javax.swing.JTable listaProductosAModificar;
    // End of variables declaration//GEN-END:variables

}
