/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppv.forms;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ppv.dbConection.DBConect;

import ppv.model.Productos;

/**
 *
 * @author user2
 */
public class BuscadorVentas extends javax.swing.JFrame {
    
    DefaultTableModel ventasEncontradosAModificar;
    Productos productoParaCarrrito=new Productos();
    Venta ventanaAnt;
    public BuscadorVentas(DefaultTableModel ventasEncontradosAModificar,Venta ventanaAnt) {
       
        this.ventasEncontradosAModificar=ventasEncontradosAModificar;
        initComponents();
        setLocationRelativeTo(null);
        //listaProductosAModificar.getColumn("Precio compra").setWidth(0);
        //listaProductosAModificar.getColumn("Precio compra").setMinWidth(0);
        //listaProductosAModificar.getColumn("Precio compra").setMaxWidth(0);
        this.ventanaAnt=ventanaAnt;
    }
    public BuscadorVentas() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaProductosAModificar = new javax.swing.JTable();
        agregarProductoAVenta = new javax.swing.JButton();

        jButton1.setText("jButton1");

        listaProductosAModificar.setModel(ventasEncontradosAModificar);
        jScrollPane5.setViewportView(listaProductosAModificar);

        agregarProductoAVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ppv/forms/1448503464_sign-error.png"))); // NOI18N
        agregarProductoAVenta.setText("Cancelar venta");
        agregarProductoAVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoAVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarProductoAVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarProductoAVenta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProductoAVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoAVentaActionPerformed
        
        int fila=listaProductosAModificar.getSelectedRowCount();
        
        if(fila==0){
            JOptionPane.showMessageDialog(null,"No has seleccionado un producto para agregar");
            return;
        }else{
            fila=listaProductosAModificar.getSelectedRow();
        } 
       
        
        
       String fecha=""+listaProductosAModificar.getValueAt(fila, 2);
       String idVenta=""+listaProductosAModificar.getValueAt(fila, 0); 
       
       cancelarProductosVenta(fecha,idVenta);
       this.setVisible(false);
       
    }//GEN-LAST:event_agregarProductoAVentaActionPerformed

    public void cancelarProductosVenta(String fecha, String idVenta){
        
        DBConect conexion=new DBConect();  
        
        try{

          Connection conexionMysql = conexion.GetConnection();

          Statement statement = conexionMysql.createStatement();
          
          
            String SQLString="SELECT a.idVenta,d.cantidad,d.Productos_idProductos as producto, p.unidadesEnCaja, "
                              + " p.cantidadVendidos FROM venta as a "+
                             " inner join detalleVenta as d on a.idVenta=d.Venta_idVenta"+
                             " inner join productos as p on p.idProductos=d.Productos_idProductos"+
                             " where a.fechaVenta='"+fecha+"' and a.consecutivoVenta="+idVenta;
            
            System.out.println(SQLString);
            
            ResultSet rs= statement.executeQuery(SQLString);
            Statement statement2 = conexionMysql.createStatement();
            while(rs.next()){
                
                Integer identificadorVenta=rs.getInt("idVenta");
                Double cantidad=rs.getDouble("cantidad");
                Integer idProducto=rs.getInt("producto");
                Double unidadesEnAlmacen=rs.getDouble("unidadesEnCaja");
                Double cantidadVendidos=rs.getDouble("cantidadVendidos");
               
                ///por cada producto que se vendio lo sumamos nuevamente al inventario
                //eliminamos el detalle de la venta y la venta
                Double cantidadEnCajaOriginal=unidadesEnAlmacen+cantidad;
          
                Double cantidadDeVendidosOriginal=cantidadVendidos-cantidad;
               
                String sqlString2="Update productos set unidadesEnCaja="+ cantidadEnCajaOriginal +
                                 " , cantidadVendidos="+cantidadDeVendidosOriginal+
                                 " where idProductos='"+idProducto+"'";

                int resultado=statement2.executeUpdate(sqlString2);
                
                if(resultado==1){
                       String sqlStringDelete="DELETE FROM detalleVenta " +
                                              " where Venta_idVenta="+identificadorVenta+"";

                       statement2.executeUpdate(sqlStringDelete);
                       
                       sqlStringDelete="DELETE FROM Venta " +
                                              " where idVenta="+identificadorVenta+"";

                       statement2.executeUpdate(sqlStringDelete);
                       
                }
                
                
            }
          
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscadorVentas().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProductoAVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane5;
    private static javax.swing.JTable listaProductosAModificar;
    // End of variables declaration//GEN-END:variables

}
